apiVersion: v2
name: bitbucket
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "6.0.9-jdk11"
home: https://www.atlassian.com/software/bitbucket
icon: https://is2-ssl.mzstatic.com/image/thumb/Purple113/v4/f6/1f/d8/f61fd8a9-5451-cd1a-8ef0-5b865999bacb/source/256x256bb.jpg
keywords:
  - bitbucket
  - bitbucket-server
  - atlassian
  - agile
  - documentation
  - wiki
sources:
  - https://bitbucket.org/atlassian-docker/docker-atlassian-bitbucket-server
  - https://hub.docker.com/r/atlassian/bitbucket
  - https://a7d33cf04bcac42209a383d094407802-637075229.us-east-2.elb.amazonaws.com/artifactory/oag-helm-virtual/
maintainers:
  - name: PickyButani
    email: PickyButani@gmail.com
dependencies:
  - name: postgresql
    version: ~10.3.17
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - Use absolute reference to JDK 11 image
